
###

GET http://localhost:3333/carros

###

POST http://localhost:3333/carros
Content-Type: application/json

{
    "marca": "",
    "cor": "",
    "placa": ""
}

###

PUT http://localhost:3333/carros/
Content-Type: application/json

{
    "marca": "",
    "cor": "",
    "placa": ""
}

###

DELETE http://localhost:3333/carros/
